consumes:
  - application/json
definitions: {
  user_model:
    type: object
    properties:
      id:
        type: integer
        format: int64
      email:
        type: string
      username:
        type: string
      display_name:
        type: string
      biography:
        type: string
      birthday:
        type: string
      old_password:
        type: string
      password:
        type: string
      password_r:
        type: string
      profile_picture:
        type: string
      points:
        type: integer
        format: int32
      date_created:
        type: string
}
info:
  description: Flash cards learning platform Users API
  title: Moku Moku Users API
  version: 0.1.0
paths: {} #define endpoints in API
produces:
  - application/json
schemes:
  - http
swagger: "2.0"
