consumes:
  - application/json
definitions:
  User:
    type: object
    required:
      - email
      - username
      - password
      - password_r
    properties:
      id:
        type: integer
        format: int64
      email:
        type: string
      username:
        type: string
      display_name:
        type: string
      biography:
        type: string
      birthday:
        type: string
      old_password:
        type: string
      password:
        type: string
      password_r:
        type: string
      profile_picture:
        type: string
      points:
        type: integer
        format: int32
      date_created:
        type: string
  RestErr:
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
        format: int
      error:
        type: string
info:
  description: Flash cards learning platform Users API
  title: Moku Moku Users API
  version: 0.1.0
paths:
  /users:
    post:
      tags: ["user"]
      operationId: createUser
      description: Stores a new user
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/User"
        - name: X-Public
          type: boolean
          in: header
          required: true
      responses:
        '200':
          description: User created
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/RestErr"
  /users/{user_id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true 
    get:
      tags:
        - user
      operationId: getUser
      description: Gets a user from the database
      responses:
        '200':
          description: User data retrieved
          schema:
            type: object
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/RestErr"

produces:
  - application/json
schemes:
  - http
  - https
swagger: "2.0"
